@REM CommitAndPushToPersonalCI.bat
@REM This script adds any untracked files and commits them and any changes to git.
@REM It then pushes the git repository changes up to the "personalci" remote repository.
@REM From there, a CI Server should pick up and run the build.

@ECHO on
@ECHO Auto-committing to Git Repository and push to PersonalCI after Successful Build.

@REM Add files that are outstanding to the local git repository.
call git add . 
@if errorlevel 1 goto :error

@REM Commit all files to the repository with an autogenerated commit message.
call git commit -a -m "Auto-commit from successful build on %COMPUTERNAME% by %USERNAME% at %TIME% on %DATE%"
@if errorlevel 1 goto :error

@REM Push to the personalci remote repository.
call git push personalci master
@if errorlevel 1 goto :error

@ECHO.
@ECHO SUCCESS: Pushed to Personal CI
@goto :exit


:error
@ECHO.
@ECHO ERROR! -- ErrorLevel: %errorLevel%


:exit