@ECHO on
@ECHO Auto-committing to Git Repository and push to PersonalCI after Successful Build.

@REM Add files that are outstanding to the local git repository.
call git add . 
@if errorlevel 1 goto :error

@REM Commit all files to the repository with an autogenerated commit message.
call git commit -a -m "Auto-commit from successful build on %COMPUTERNAME% by %USERNAME% at %TIME% on %DATE%"
@if errorlevel 1 goto :error

@REM Push to the personalci remote repository.
call git push personalci master
@if errorlevel 1 goto :error

@ECHO SUCCESSFULY PUSHED TO PERSONAL CI.
@goto :exit


:error
@ECHO AN ERROR OCCURRED - %errorLevel%

:exit
@ECHO.
@ECHO.