@ECHO on
@ECHO.
@ECHO Auto-committing to Git Repository after Successful Build.
@ECHO ---------------------------------------------------------

@REM Add files that are outstanding to the local git repository.
call git add . 
@if errorlevel 1 goto :error

@REM Commit all files to the repository with an autogenerated commit message.
call git commit -a -m "Auto-commit from successful build on %COMPUTERNAME% by %USERNAME% at %TIME% on %DATE%"
@if errorlevel 1 goto :error


@ECHO.
@ECHO Pushing to PersonalCi repository.
@ECHO ---------------------------------

@REM Push to the personalci remote repository.
call git push personalci master
@if errorlevel 1 goto :error


@ECHO.
@ECHO Completed Successfully!
@goto :exit


:error
@ECHO An error occured - %errorLevel%

:exit
@ECHO.